### ISSUE TITLE
`terraform plan` outputs `api_secret` in plain text

### ISSUE THREAD

**Issue by s-hashimo** [authlete/terraform-provider-authlete#165]
Since we're running Terraform on CI, we don't want to output `api_secret` in plain text.

### Terraform Version
1.9.7

### Affected Resource(s)
- authlete_service

### Terraform Configuration Files
```hcl
import {
  id = "111111111111111"
  to = authlete_service.as
}

resource "authlete_service" "as" {
  issuer = "https://as.mydomain.com"
  service_name = "MyDomainAS"
  description = "A terraform based service for managing the Authlete based OAuth server"
  supported_grant_types = ["AUTHORIZATION_CODE"]
  supported_response_types = ["CODE"]
}
```

### Expected Behavior

```hcl
        api_secret                                       = (sensitive value)
```

### Actual Behavior

```hcl
        api_secret                                       = "gBL_xxxxxxxxxxxxxxxxxxxx"
```

### Steps to Reproduce

1. Define `authlete_service` and [import block](https://developer.hashicorp.com/terraform/language/import).
2. Run `terraform plan`

> [!NOTE]
> For simple creation (=no `import` block), API Key/Secret has not been generated.
> 
> ```hcl
>       + api_secret                                  = (known after apply)
> ```

**Comment by hefa** [comment]
@s-hashimo Thank you for reporting this issue, we will investigate it quickly.

**Comment by s-hashimo** [comment]
Thanks for quick response.
And sorry, my "Steps to Reproduce" is incorrect. 🙈 

I updated it.
