### ISSUE TITLE
Is there any plan to publish this provider to the public Terraform registry?

### ISSUE THREAD

**Issue by grezar** [authlete/terraform-provider-authlete#28]
Hi there.
I'm looking to if there is Authelete terraform provider to manage our configuration.
This provider seems to be officially developed but still hasn't been published to the public Terraform registry yet.
It would be great if it's supported so that users can use this provider usefully as well as other providers.
So, I want to ask is there any plan to publish this provider to the public Terraform registry or not?
Thank you.

**Comment by hefa** [comment]
Hi grezar,
Yes, this will be published to the Terraform registry within the coming months, once development is finished and it's been through enough testing.

**Comment by hefa** [comment]
@grezar @ryokotmng Hi, just wanted to let you know that we have published v0.3.0 to [Terraform registry](https://registry.terraform.io/providers/authlete/authlete/latest) now. We are not yet calling it GA, but you can start using this for development. We will continue testing before calling it 1.0. Please let us know if you run into any issues!

**Comment by grezar** [comment]
Thanks!
Happy to hear that 👯
