### ISSUE TITLE
When is this provider scheduled to be GA?

### ISSUE THREAD

**Issue by mf-sakura** [authlete/terraform-provider-authlete#51]
Hi there.

Can you announce some information about the roadmap to GA?
I want to use this provider on the production environment if possible.

Thank you.

**Comment by hefa** [comment]
@mf-sakura Hi, we are aiming to release version 1.0 by the end of June. Before calling it GA we want to switch over our internal CI infrastructure (which runs through the OIDF conformance suite multiple times daily) to using the provider, so that we can be assured of its reliable functioning.
